name: Generate new URL List
run-name: generate new url list
on: 
  schedule:
    - cron: '0 0 * * 3'  # Runs every Wednesday at 12:00 AM UTC
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: ./run.sh
  push_updated_list:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v5